# Generated by Django 3.0.5 on 2020-04-07 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('IdentityDocumentNumber', models.TextField()),
                ('DateOfBirth', models.DateTimeField()),
                ('DateCaseConfirmed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationVisited', models.TextField()),
                ('Address', models.TextField()),
                ('District', models.TextField()),
                ('XCoord', models.TextField()),
                ('YCoord', models.TextField()),
                ('DateFrom', models.DateTimeField()),
                ('DateTo', models.DateTimeField()),
                ('Detail', models.TextField()),
                ('Category', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.patient')),
            ],
        ),
    ]
